#!bin/sh

clear;clear
echo "Removing old program..."
rm test

echo "Compiling new program..."
nvcc -o test                  \
                              \
    temp_test.cu             # \
#                              \
#    -std=c++11                \
#    -pthread                  \
#    -g                        \
#    -O0


echo "Running Program..."
echo " "
./test
echo " "
echo "Program Ended..."

